apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-sample
  name: deploy-prometheus-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-sample
  template:
    metadata:
      annotations:
        prometheus.app.ci.com: "true"
      labels:
        app: prometheus-sample
      name: sample
    spec:
      containers:
      - args:
        - --storage.tsdb.retention.time=5d
        - --config.file=/etc/config/prometheus.yml
        - --storage.tsdb.path=/data
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        image: prom/prometheus:latest
        imagePullPolicy: IfNotPresent
        name: prometheus
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data
          name: storage-volume
      - args:
        - --volume-dir=/etc/config
        - --webhook-url=http://127.0.0.1:9090/-/reload
        image: jimmidyson/configmap-reload:v0.2.2
        imagePullPolicy: IfNotPresent
        name: prometheus-server-configmap-reload
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-for-app
        name: config-volume
      - emptyDir: {}
        name: storage-volume
